# Generated by Django 4.1.7 on 2023-03-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_delete_entregable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
